doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
          short_string:  App\Shared\Infrastructure\Persistence\Doctrine\Type\NameType
          long_string:  App\Shared\Infrastructure\Persistence\Doctrine\Type\LongTextType
          uuid: App\Shared\Infrastructure\Persistence\Doctrine\Type\UuidType
          birth_date_type: App\Shared\Infrastructure\Persistence\Doctrine\Type\DoctrineBirthDateType
          token_type: App\Shared\Infrastructure\Persistence\Doctrine\Type\TokenType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
          lotr_context:
            mapping: true
            is_bundle: false
            type: xml
            dir: '%kernel.project_dir%/src/LotrContext/Infrastructure/Persistence/Doctrine/Entity'
            prefix: 'App\LotrContext\Domain\Aggregate'
          user_context:
            mapping: true
            is_bundle: false
            type: xml
            dir: '%kernel.project_dir%/src/UserContext/Infrastructure/Persistence/Doctrine/Entity'
            prefix: 'App\UserContext'

when@test:
    doctrine:
        dbal:
          url: '%env(resolve:DATABASE_URL)%'
          # "TEST_TOKEN" is typically set by ParaTest
          dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
