fos_rest:
  format_listener:
    rules:
      - path: ~
        host: ~
        prefer_extension: false
        fallback_format: json

  view:
    view_response_listener: force

  exception:
    enabled: true

  serializer:
    serialize_null: true

  body_listener:
    enabled: true
