services:
  php:
    hostname: php
    container_name: api-coding-task-php
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
      - XDEBUG_MODE=coverage
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/var/www
    networks:
      - bridge
  db:
    hostname: db
    container_name: api-coding-task-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lotr
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    networks:
      - bridge
  redis:
    container_name: api-coding-task-redis
    image: redis:7.2-alpine3.19
    ports:
      - "6379:6379"
    networks:
        - bridge
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
  swagger-ui:
    container_name: api-coding-task-swagger-ui
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./doc/openapi:/usr/share/nginx/html/swagger
    environment:
      - API_URL=/swagger/openapi.yaml
    networks:
      - bridge
  rabbitmq:
    container_name: api-coding-task-rabbitmq
    image: rabbitmq:3.9-management-alpine
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
        - bridge

networks:
  bridge:

volumes:
  database_data:
