version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
      docker: "true"
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
    networks:
      - bridge
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./opt/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lotr
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    networks:
      - bridge
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./doc/openapi:/usr/share/nginx/html/swagger
    environment:
      - API_URL=/swagger/openapi.yaml
    networks:
      - bridge

networks:
  bridge:
