lotr_context.rest.faction.create_faction.page:
  path: /factions
  methods: POST
  controller: 'App\LotrContext\Infrastructure\Delivery\Rest\Faction\CreateFactionPage'
lotr_context.rest.faction.fetch_faction.page:
  path: /factions/{id}
  methods: GET
  controller: 'App\LotrContext\Infrastructure\Delivery\Rest\Faction\FetchFactionPage'