# FACTION ROUTES
lotr_context.rest.faction.create_faction.page:
  path: /factions
  methods: POST
  controller: 'App\LotrContext\Infrastructure\Delivery\Rest\Faction\CreateFactionPage'
lotr_context.rest.faction.fetch_faction.page:
  path: /factions/{id}
  methods: GET
  controller: 'App\LotrContext\Infrastructure\Delivery\Rest\Faction\FetchFactionPage'
lotr_context.rest.faction.list_faction.page:
  path: /factions
  methods: GET
  controller: 'App\LotrContext\Infrastructure\Delivery\Rest\Faction\ListFactionPage'
lotr_context.rest.faction.update_faction.page:
  path: /factions/{id}
  methods: PUT
  controller: 'App\LotrContext\Infrastructure\Delivery\Rest\Faction\UpdateFactionPage'
lotr_context.rest.faction.delete_faction.page:
  path: /factions/{id}
  methods: DELETE
  controller: 'App\LotrContext\Infrastructure\Delivery\Rest\Faction\DeleteFactionPage'


# EQUIPMENT ROUTES
lotr_context.rest.equipment.create_equipment.page:
  path: /equipments
  methods: POST
  controller: 'App\LotrContext\Infrastructure\Delivery\Rest\Equipment\CreateEquipmentPage'
lotr_context.rest.equipment.fetch_equipment.page:
  path: /equipments/{id}
  methods: GET
  controller: 'App\LotrContext\Infrastructure\Delivery\Rest\Equipment\FetchEquipmentPage'
lotr_context.rest.equipment.delete_equipment.page:
  path: /equipments/{id}
  methods: DELETE
  controller: 'App\LotrContext\Infrastructure\Delivery\Rest\Equipment\DeleteEquipmentPage'
lotr_context.rest.equipment.list_equipment.page:
  path: /equipments
  methods: GET
  controller: 'App\LotrContext\Infrastructure\Delivery\Rest\Equipment\ListEquipmentPage'
lotr_context.rest.equipment.update_equipment.page:
  path: /equipments/{id}
  methods: PUT
  controller: 'App\LotrContext\Infrastructure\Delivery\Rest\Equipment\UpdateEquipmentPage'


# CHARACTER ROUTES
lotr_context.rest.character.create_character.page:
  path: /characters
  methods: POST
  controller: 'App\LotrContext\Infrastructure\Delivery\Rest\Character\CreateCharacterPage'
lotr_context.rest.character.fetch_character.page:
  path: /characters/{id}
  methods: GET
  controller: 'App\LotrContext\Infrastructure\Delivery\Rest\Character\FetchCharacterPage'
lotr_context.rest.character.list_equipment.page:
  path: /characters
  methods: GET
  controller: 'App\LotrContext\Infrastructure\Delivery\Rest\Character\ListCharacterPage'
lotr_context.rest.character.delete_character.page:
  path: /characters/{id}
  methods: DELETE
  controller: 'App\LotrContext\Infrastructure\Delivery\Rest\Character\DeleteCharacterPage'