name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lotr
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=root"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo_mysql

      - name: Clear Composer cache
        run: composer clear-cache

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Import init-test.sql
        run: |
          mysql -h 127.0.0.1 -u root --password=root < opt/db/init-test.sql

      - name: Run tests
        run: |
          export DB_HOST=db
          export DB_DATABASE=lotr_test
          export DATABASE_URL="mysql://root:root@db:3306/lotr?serverVersion=8.0.32&charset=utf8mb4"
          ./vendor/bin/phpunit
          ./vendor/bin/behat --no-snippets --strict --colors


